on: push
jobs: 
  build-and-test: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 
    - name: build
      run: | 
        chmod +x "${GITHUB_WORKSPACE}/build.sh"
        "${GITHUB_WORKSPACE}/build.sh"
        echo %errorlevel%
